"""Disclosure note and internal policy snippets."""

from __future__ import annotations

from agent.parser import AgentLog


def generate_disclosure_note(log: AgentLog) -> str:
    operator = log.operator or "[operator name]"
    scope = log.scope or "the limited scope described by the organization"
    return (
        f"This message was prepared by an AI assistant operated by {operator}. "
        f"The assistant works only within this scope: {scope}. "
        "You may request review by a human representative before any decision is made."
    )


def generate_policy_snippet(gaps: list[str]) -> str:
    lines = [
        "### Internal AI Agent Disclosure Policy — draft snippet",
        "",
        "1. Every external message generated by an AI agent must clearly state that AI was used.",
        "2. Every AI-agent message must identify the responsible operator or organization.",
        "3. Medium, high and critical-risk actions require human review before execution.",
        "4. The organization must preserve logs sufficient to reconstruct the agent action, timestamp, tool use and approval status.",
        "5. AI agents must not provide legal, medical, tax or other reserved professional advice without qualified human review.",
    ]
    if gaps:
        lines += ["", "Priority remediation based on this audit:"]
        for gap in gaps:
            lines.append(f"- Address: {gap}.")
    return "\n".join(lines)
